begin;
create table if not exists public.avisos_operacao (
 id integer primary key check(id=1),
 mensagem text not null default '' check(length(mensagem)<=3000),
 bloqueado boolean not null default false,
 atualizado_por uuid,
 atualizado_em timestamptz not null default now(),
 check(not bloqueado or length(trim(mensagem))>0)
);
insert into public.avisos_operacao(id) values(1) on conflict do nothing;
alter table public.avisos_operacao enable row level security;
revoke all on public.avisos_operacao from public,anon,authenticated;
grant select,insert,update on public.avisos_operacao to service_role;
create table if not exists public.avisos_modelos (
 id bigint generated by default as identity primary key,
 titulo text not null check(length(titulo) between 1 and 120),
 mensagem text not null check(length(mensagem) between 1 and 3000),
 atualizado_por uuid,
 criado_em timestamptz not null default now()
);
alter table public.avisos_modelos enable row level security;
revoke all on public.avisos_modelos from public,anon,authenticated;
grant select,insert,update,delete on public.avisos_modelos to service_role;
grant usage, select, update on sequence public.avisos_modelos_id_seq to service_role;
grant usage on schema public to service_role;
insert into public.avisos_modelos(titulo,mensagem) select * from (values
 ('Bom dia de trabalho','Bom dia de trabalho! A equipe está disponível para apoiar as rotas de hoje.'),
 ('Atenção às evidências','Atenção: siga o checklist, registre as evidências e confira os materiais antes de finalizar.'),
 ('Manutenção do sistema','Aviso: o sistema estará em manutenção. Aguarde a liberação antes de enviar relatórios.')
) as modelos(titulo,mensagem) where not exists(select 1 from public.avisos_modelos);
commit;
