begin;
create table if not exists public.auditoria_gestao (
  id bigint generated by default as identity primary key,
  acao text not null check (length(acao) between 1 and 120),
  metodo text not null check (length(metodo) between 1 and 12),
  rota text not null check (length(rota) between 1 and 300),
  resultado text not null default 'sucesso',
  usuario_id uuid,
  usuario_email text,
  criado_em timestamptz not null default now()
);
create index if not exists auditoria_gestao_criado_em_idx on public.auditoria_gestao (criado_em desc);
create index if not exists auditoria_gestao_usuario_idx on public.auditoria_gestao (usuario_id, criado_em desc);
alter table public.auditoria_gestao enable row level security;
revoke all on public.auditoria_gestao from public, anon, authenticated;
grant select, insert on public.auditoria_gestao to service_role;
commit;
